# Generated by Django 5.2.7 on 2025-11-18 03:30

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0007_tema_external_id_alter_tema_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ley',
            name='contenido_pdf',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ley',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024, null=True),
        ),
    ]
