# Generated by Django 5.2.7 on 2025-11-18 15:24

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0008_ley_contenido_pdf_ley_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('leyes', models.JSONField()),
                ('mensajes', models.JSONField()),
                ('resumen', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
