# Generated by Django 5.2.7 on 2025-11-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0010_alter_pregunta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
