# Generated by Django 5.2.7 on 2025-11-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0011_alter_pregunta_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='mensajes',
        ),
    ]
