# Generated by Django 5.2.7 on 2025-11-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leyes', '0012_remove_pregunta_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ley',
            name='resumen',
            field=models.TextField(blank=True),
        ),
    ]
